import { extendZodWithOpenApi } from "@asteasolutions/zod-to-openapi";
import { z } from "zod";
import { registry } from "../../openapi/registry";

extendZodWithOpenApi(z);

// ── Response envelope helper ────────────────────────────────────────────────

const ApiResponseSchema = <T extends z.ZodTypeAny>(data: T) =>
  z.object({
    ok: z.boolean().openapi({ example: true }),
    status: z.enum(["success", "error"]).openapi({ example: "success" }),
    code: z.number().openapi({ example: 200 }),
    message: z.string().openapi({ example: "OK" }),
    data: data.optional(),
    accessToken: z.string().optional(),
  });

// ── Domain schemas ──────────────────────────────────────────────────────────

// Air quality response generated by the Gemini AI model from PM2.5 sensor data.
// `quality` may be an empty string in fallback/error scenarios (e.g. no sensor
// in the requested area).
export const AIResponseSchema = z
  .object({
    description: z.string().openapi({
      example: "目前空氣品質良好,適合外出活動。",
    }),
    quality: z
      .enum([
        "GOOD",
        "MODERATE",
        "UNHEALTHY_SENSITIVE",
        "UNHEALTHY",
        "VERY_UNHEALTHY",
        "HAZARDOUS",
        "",
      ])
      .openapi({ example: "GOOD" }),
  })
  .openapi("AIResponse");

export const AirQualityResponseSchema = ApiResponseSchema(AIResponseSchema).openapi(
  "AirQualityResponse"
);

// ── OpenAPI path registrations ──────────────────────────────────────────────

registry.registerPath({
  method: "get",
  path: "/air/air-quality",
  tags: ["Air Quality"],
  summary: "目前空氣品質",
  description:
    "依座標回傳由 Gemini 依 PM2.5 感測資料生成的空品說明，無資料時 quality 為空。",
  request: {
    query: z.object({
      lat: z
        .union([z.string(), z.number()])
        .openapi({ example: 25.0478, description: "地點緯度。" }),
      lng: z
        .union([z.string(), z.number()])
        .openapi({ example: 121.5319, description: "地點經度。" }),
    }),
  },
  responses: {
    200: {
      description: "空氣品質資料",
      content: {
        "application/json": { schema: AirQualityResponseSchema },
      },
    },
    500: { description: "伺服器錯誤" },
  },
});
