import { extendZodWithOpenApi } from "@asteasolutions/zod-to-openapi";
import { z } from "zod";
import { registry } from "../../openapi/registry";

extendZodWithOpenApi(z);

// ── Response envelope helper ────────────────────────────────────────────────

const ApiResponseSchema = <T extends z.ZodTypeAny>(data: T) =>
  z.object({
    ok: z.boolean().openapi({ example: true }),
    status: z.enum(["success", "error"]).openapi({ example: "success" }),
    code: z.number().openapi({ example: 200 }),
    message: z.string().openapi({ example: "OK" }),
    data: data.optional(),
    accessToken: z.string().optional(),
  });

// ── Domain schemas ──────────────────────────────────────────────────────────

// Air quality response generated by the Gemini AI model from PM2.5 sensor data.
// `quality` may be an empty string in fallback/error scenarios (e.g. no sensor
// in the requested area).
export const AIResponseSchema = z
  .object({
    description: z.string().openapi({
      example: "目前空氣品質良好,適合外出活動。",
    }),
    quality: z
      .enum([
        "GOOD",
        "MODERATE",
        "UNHEALTHY_SENSITIVE",
        "UNHEALTHY",
        "VERY_UNHEALTHY",
        "HAZARDOUS",
        "",
      ])
      .openapi({ example: "GOOD" }),
  })
  .openapi("AIResponse");

export const AirQualityResponseSchema = ApiResponseSchema(AIResponseSchema).openapi(
  "AirQualityResponse"
);

// ── OpenAPI path registrations ──────────────────────────────────────────────

registry.registerPath({
  method: "get",
  path: "/air/air-quality",
  tags: ["Air Quality"],
  summary: "Current air quality",
  description:
    "Returns the latest AQI and pollutant readings for Taipei. The response data is generated by Gemini AI based on PM2.5 sensor data from Taiwan's STA API. If no sensor data is available in the requested area, a fallback is returned with an empty `quality` field.",
  request: {
    query: z.object({
      lat: z
        .union([z.string(), z.number()])
        .openapi({ example: 25.0478, description: "Latitude of the location." }),
      lng: z
        .union([z.string(), z.number()])
        .openapi({ example: 121.5319, description: "Longitude of the location." }),
    }),
  },
  responses: {
    200: {
      description: "Air quality data",
      content: {
        "application/json": { schema: AirQualityResponseSchema },
      },
    },
    500: { description: "Internal error" },
  },
});
